//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceCMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tehsil
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Name_Mar { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<int> State_ID { get; set; }
        public Nullable<int> District_ID { get; set; }
    }
}
