//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceCMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAttendence
    {
        public int AttendenceID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ReferenceID { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<System.DateTime> OutDateTime { get; set; }
        public Nullable<double> InLat { get; set; }
        public Nullable<double> InLong { get; set; }
        public Nullable<double> OutLat { get; set; }
        public Nullable<double> OutLong { get; set; }
        public string InImage { get; set; }
        public string OutImage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
