//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceCMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string EmployeeID { get; set; }
        public string LoginId { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Gender { get; set; }
        public string Qualification { get; set; }
        public string Experience { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Aadhar { get; set; }
        public string PAN { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string ProfileImage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
